#pragma once

// #define MASTER_RIGHT
#define MASTER_LEFT
// #define SPLIT_USB_DETECT
// #define EE_HANDS 
#define DYNAMIC_KEYMAP_LAYER_COUNT 5

// #define USE_SERIAL
#define ENCODER_RESOLUTION 2
// #define SPLIT_TRANSPORT_MIRROR
// #define SOFT_SERIAL_PIN E6
// #define SERIAL_USE_MULTI_TRANSACTION

// #define SPLIT_HAND_PIN GP23

// #define USB_VBUS_PIN GP18

// #define SERIAL_ _FULL_DUPLEX
// #define SERIAL_USART_TX_PIN GP8
// #define SERIAL_USART_RX_PIN GP9
// #define SERIAL_USART_PIN_SWAP

// #define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
// #define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
